services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
#        depends_on:
#            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel
    #    Se estiver dando erro na conexão com o banco utilizando o PHPStorm (DataGrip), basta na tela de parametrização da conexão ao banco clicar em Advanced ->  useSSL (setar como false).
    #    ao fazer a conexão com o banco de dados, é importante conectar a porta 3388, pois é a porta da maquina, que está escutando a porta 3306 do container.
    # db mysql

    #se passar por um erro com allowPublicKeyRetrieval, fazer a conexão com o banco dessa forma na URL
    # exemplo -> jdbc:mysql://localhost:3388/laravel?allowPublicKeyRetrieval=true&useSSL=false
    db:
        image: mysql:8.0
#        platform: linux/x86_64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3300:3306"
        networks:
            - laravel

    # PHPMyAdmin
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        platform: linux/x86_64
#        restart: unless-stopped
#        ports:
#            - "8080:80"
#        environment:
#            PMA_HOST: db
#            PMA_PORT: 3306
#            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
#        networks:
#            - laravel

    # redis
#    redis:
#        image: redis:latest
#        networks:
#            - laravel

networks:
    laravel:
        driver: bridge
